# Generated by Django 3.2.8 on 2021-11-24 20:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import raktar.models.dokumentum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bevetel_riport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termek_id', models.CharField(max_length=255)),
                ('termek_nev', models.CharField(max_length=255)),
                ('gyari_cikkszam', models.CharField(max_length=255)),
                ('sajat_cikkszam', models.CharField(max_length=255)),
                ('beszallito_nev', models.CharField(max_length=255)),
                ('raktar_nev', models.CharField(max_length=255)),
                ('bevetel_mennyiseg', models.CharField(max_length=255)),
                ('ar_bevetel_netto', models.CharField(max_length=255)),
                ('bevetel_datum', models.CharField(max_length=255)),
                ('szallitolevel_szam', models.CharField(max_length=255)),
                ('megjegyzes', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('azonosito', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bevetel_riport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ertekesit_riport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termek_id', models.CharField(max_length=255)),
                ('azonosito', models.CharField(max_length=255)),
                ('termek_nev', models.CharField(max_length=255)),
                ('gyari_cikkszam', models.CharField(max_length=255)),
                ('sajat_cikkszam', models.CharField(max_length=255)),
                ('raktar_nev', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('megjegyzes', models.CharField(max_length=255)),
                ('eladas_mennyiseg', models.CharField(max_length=255)),
                ('ar_eladas_brutto', models.CharField(max_length=255)),
                ('eladas_datum', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ertekesit_riport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='keszlet_riport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termek_id', models.CharField(max_length=255)),
                ('termek_nev', models.CharField(max_length=255)),
                ('gyari_cikkszam', models.CharField(max_length=255)),
                ('sajat_cikkszam', models.CharField(max_length=255)),
                ('raktar_nev', models.CharField(max_length=255)),
                ('keszlet', models.CharField(max_length=255)),
                ('mennyisegi_egyseg', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'keszlet_riport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Termek_Osszdb',
            fields=[
                ('termek_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('termek_nev', models.CharField(max_length=255)),
                ('sajat_cikkszam', models.CharField(max_length=255)),
                ('gyari_cikkszam', models.CharField(max_length=255)),
                ('min_keszlet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keszlet', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'termek_osszdb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='termek_riport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termek_nev', models.CharField(max_length=255)),
                ('gyari_cikkszam', models.CharField(max_length=255)),
                ('sajat_cikkszam', models.CharField(max_length=255)),
                ('ar_web_netto', models.CharField(max_length=255)),
                ('ar_bolt_brutto', models.CharField(max_length=255)),
                ('elhelyezes', models.CharField(max_length=255)),
                ('min_keszlet', models.CharField(max_length=255)),
                ('mennyisegi_egyseg', models.CharField(max_length=255)),
                ('web_link', models.CharField(max_length=255)),
                ('termekkategoria', models.CharField(max_length=255)),
                ('termekgyarto', models.CharField(max_length=255)),
                ('megjegyzes', models.CharField(max_length=255)),
                ('aktiv', models.BooleanField()),
            ],
            options={
                'db_table': 'termek_riport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Beallitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alap_aruhaz_nev', models.CharField(blank=True, max_length=255, null=True)),
                ('alap_aruhaz_KEY', models.CharField(blank=True, max_length=255, null=True)),
                ('alap_aruhaz_aktiv', models.BooleanField(default=False)),
                ('masodik_aruhaz_nev', models.CharField(blank=True, max_length=255, null=True)),
                ('masodik_aruhaz_KEY', models.CharField(blank=True, max_length=255, null=True)),
                ('masodik_aruhaz_aktiv', models.BooleanField(default=False)),
                ('harmadik_aruhaz_nev', models.CharField(blank=True, max_length=255, null=True)),
                ('harmadik_aruhaz_KEY', models.CharField(blank=True, max_length=255, null=True)),
                ('harmadik_aruhaz_aktiv', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Beállítások',
            },
        ),
        migrations.CreateModel(
            name='Beszallito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beszallito_nev', models.CharField(max_length=255)),
                ('beszallito_cim', models.CharField(blank=True, max_length=255, null=True)),
                ('beszallito_ugyintezo', models.CharField(blank=True, max_length=255, null=True)),
                ('beszallito_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('beszallito_telefon', models.CharField(blank=True, max_length=255, null=True)),
                ('megjegyzes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Beszállítók',
            },
        ),
        migrations.CreateModel(
            name='Dokumentum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termek_id', models.IntegerField()),
                ('felt_datum', models.DateField()),
                ('dok_nev', models.CharField(max_length=255)),
                ('dokfile', models.FileField(upload_to=raktar.models.dokumentum.content_file_name)),
            ],
            options={
                'verbose_name_plural': 'Dokumentumok',
            },
        ),
        migrations.CreateModel(
            name='Raktar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raktar_nev', models.CharField(max_length=255, unique=True)),
                ('megjegyzes', models.TextField(blank=True, null=True)),
                ('user', models.ManyToManyField(related_name='user_raktar', related_query_name='raktarjog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Raktárak',
                'ordering': ('raktar_nev',),
            },
        ),
        migrations.CreateModel(
            name='TermekGyarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termekgyarto', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Termék gyártók',
                'ordering': ('termekgyarto',),
            },
        ),
        migrations.CreateModel(
            name='TermekKategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termekkategoria', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Termék kategóriák',
                'ordering': ('termekkategoria',),
            },
        ),
        migrations.CreateModel(
            name='Termek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termek_nev', models.CharField(max_length=255)),
                ('gyari_cikkszam', models.CharField(max_length=255)),
                ('sajat_cikkszam', models.CharField(blank=True, max_length=255, null=True)),
                ('ar_nagyker_netto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('alap_bolt_ar_brutto', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('masodik_bolt_ar_brutto', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('harmadik_bolt_ar_brutto', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('elhelyezes', models.CharField(blank=True, max_length=255, null=True)),
                ('min_keszlet', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('mennyisegi_egyseg', models.CharField(choices=[('', 'Kérem válasszon'), ('csomag', 'csomag'), ('db', 'db'), ('kg', 'kilogramm'), ('méter', 'Méter')], max_length=255)),
                ('web_link', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('megjegyzes', models.TextField(blank=True, null=True)),
                ('nagyker_keszlet', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('alap_aruhaz', models.BooleanField(default=False)),
                ('masodik_aruhaz', models.BooleanField(default=False)),
                ('harmadik_aruhaz', models.BooleanField(default=False)),
                ('aktiv', models.BooleanField(default=True)),
                ('termekgyarto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='raktar.termekgyarto')),
                ('termekkategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='raktar.termekkategoria')),
            ],
            options={
                'verbose_name_plural': 'Termékek',
                'unique_together': {('gyari_cikkszam', 'termek_nev')},
            },
        ),
        migrations.CreateModel(
            name='Ertekesit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eladas_mennyiseg', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ar_eladas_brutto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('eladas_datum', models.DateField()),
                ('megjegyzes', models.TextField(blank=True, null=True)),
                ('raktar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='raktar.raktar')),
                ('termek', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='raktar.termek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_ertekesit', related_query_name='ertekesito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Értékesítések',
            },
        ),
        migrations.CreateModel(
            name='Bevetel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bevetel_mennyiseg', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ar_bevetel_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bevetel_datum', models.DateField()),
                ('szallitolevel_szam', models.CharField(blank=True, max_length=255, null=True)),
                ('megjegyzes', models.TextField(blank=True, null=True)),
                ('beszallito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='raktar.beszallito')),
                ('raktar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='raktar.raktar')),
                ('termek', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='raktar.termek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_bevetel', related_query_name='bevetelezo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bevételezés',
            },
        ),
        migrations.CreateModel(
            name='Raktarkeszlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keszlet', models.DecimalField(decimal_places=2, max_digits=9)),
                ('raktar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='raktar.raktar')),
                ('termek', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='raktar.termek')),
            ],
            options={
                'verbose_name_plural': 'Raktárkészlet',
                'unique_together': {('termek', 'raktar')},
            },
        ),
    ]
