# Generated by Django 3.2.8 on 2021-11-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raktar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beallitas',
            name='alap_aruhaz_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beallitas',
            name='alap_aruhaz_kezdeti_arszinkron',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beallitas',
            name='harmadik_aruhaz_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beallitas',
            name='harmadik_aruhaz_kezdeti_arszinkron',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beallitas',
            name='masodik_aruhaz_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beallitas',
            name='masodik_aruhaz_kezdeti_arszinkron',
            field=models.BooleanField(default=False),
        ),
    ]
